---
galaxy_info:
  role_name: ocp4_workload_ibm_fusion
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Workload to deploy IBM Fusion onto OpenShift 4
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
