---
# -----------------------------------
# IBM Storage Fusion operator
# -----------------------------------
ocp4_workload_ibm_fusion_catalog_source_tag: latest
ocp4_workload_ibm_fusion_channel: "v2.0"
ocp4_workload_ibm_fusion_starting_csv: ""
#  ocp4_workload_ibm_fusion_starting_csv: "v2.12.0"
# OpenShift 4.20 is the latest supported version for IBM Fusion 2.12.0

# This MUST be false for IBM Fusion
ocp4_workload_ibm_fusion_installplan_approval: false

# The entitlement key needs to come from a vault, include, etc.
ocp4_workload_ibm_fusion_entitlement_key: ""

# Enable Global Data Platform
ocp4_workload_ibm_fusion_deploy_global_data_platform: false

# --------------------------------
# ODF Manager system parameters
# --------------------------------
ocp4_workload_ibm_fusion_storage_class: gp3-csi
ocp4_workload_ibm_fusion_storage_size: 512Gi
ocp4_workload_ibm_fusion_storage_cluster_deploy_timeout: 600
ocp4_workload_ibm_fusion_storage_system_deploy_timeout: 600

# --------------------------------
# Storage classes
# --------------------------------
ocp4_workload_ibm_fusion_update_default_storage_class: true
# ocp4_workload_ibm_fusion_new_default_storage_class_name: ibm-spectrum-fusion-mgmt-sc
ocp4_workload_ibm_fusion_new_default_storage_class_name: ocs-storagecluster-ceph-rbd

# -----------------------------------
# Additional Fusion Service Instances
# -----------------------------------
# Make sure you have enough CPU and Memory before enabling these
ocp4_workload_ibm_fusion_deploy_data_cataloging: false
ocp4_workload_ibm_fusion_deploy_backup_restore: false
ocp4_workload_ibm_fusion_deploy_content_aware_storage: false

ocp4_workload_ibm_fusion_data_cataloging_storage_class: ibm-spectrum-fusion-mgmt-sc
ocp4_workload_ibm_fusion_backup_restore_storage_class: ibm-spectrum-fusion-mgmt-sc
ocp4_workload_ibm_fusion_content_aware_storage_storage_class: ibm-spectrum-fusion-mgmt-sc
