---
- name: Deploy FusionServiceInstance backup-restore
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'fusionserviceinstance_backup_restore.yml.j2') | from_yaml }}"

- name: Wait for FusionServiceInstance to be fully deployed
  kubernetes.core.k8s_info:
    api_version: service.isf.ibm.com/v1
    kind: FusionServiceInstance
    name: ibm-backup-restore-service-instance
    namespace: ibm-spectrum-fusion-ns
  register: r_fusionserviceinstance
  until:
  - r_fusionserviceinstance.resources is defined
  - r_fusionserviceinstance.resources | length > 0
  - r_fusionserviceinstance.resources[0].status is defined
  - r_fusionserviceinstance.resources[0].status.health is defined
  - r_fusionserviceinstance.resources[0].status.health == "Healthy"
  retries: 120
  delay: 5

# TBD (maybe): Configure Backup/Restore agent
