---
- name: Deploy FusionServiceInstance content aware storage
  kubernetes.core.k8s:
    state: present
    template: fusionserviceinstance_cas.yml.j2
  register: r_fusionserviceinstance
  retries: 100
  delay: 10
  until: r_fusionserviceinstance is success

- name: Wait for FusionServiceInstance to be fully deployed
  kubernetes.core.k8s_info:
    api_version: service.isf.ibm.com/v1
    kind: FusionServiceInstance
    name: ibm-cas-service-instance
    namespace: ibm-spectrum-fusion-ns
  register: r_fusionserviceinstance
  until:
  - r_fusionserviceinstance.resources is defined
  - r_fusionserviceinstance.resources | length > 0
  - r_fusionserviceinstance.resources[0].status is defined
  - r_fusionserviceinstance.resources[0].status.health is defined
  - r_fusionserviceinstance.resources[0].status.health == "Healthy"
  retries: 120
  delay: 5
