---
_ocp4_workload_ibm_fusion_authority_content: ""
_ocp4_workload_ibm_fusion_decoded_dockerconfigjson: ""
_ocp4_workload_ibm_fusion_merged_dockerconfigjson: ""
_ocp4_workload_ibm_fusion_label_selector_list: []
_ocp4_workload_ibm_fusion_worker_nodes: []
